---
version: 1.6.4
name: Headset • Simple music player for YouTube
description: Some description
url: https://headsetapp.co
repository: https://github.com/headsetapp/headset-electron
twitter:
  username: headsetapp
exclude:
- ".gitignore"
- CNAME
- readme.md